# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](https://github.com/p-0rridge/lab-neural-networks/blob/master/your-code/tttboard.jpg?raw=1)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [67]:
!git clone https://github.com/p-0rridge/lab-neural-networks

fatal: destination path 'lab-neural-networks' already exists and is not an empty directory.

In [68]:
import pandas as pd
import numpy as np

In [69]:
ttt_dataframe = pd.read_csv("/content/lab-neural-networks/your-code/tic-tac-toe.csv")

1. Inspect the dataset

In [70]:
ttt_dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 958 entries, 0 to 957
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   TL      958 non-null    object
 1   TM      958 non-null    object
 2   TR      958 non-null    object
 3   ML      958 non-null    object
 4   MM      958 non-null    object
 5   MR      958 non-null    object
 6   BL      958 non-null    object
 7   BM      958 non-null    object
 8   BR      958 non-null    object
 9   class   958 non-null    bool
dtypes: bool(1), object(9)
memory usage: 68.4+ KB

In [71]:
ttt_dataframe.isna().sum()

TL       0
TM       0
TR       0
ML       0
MM       0
MR       0
BL       0
BM       0
BR       0
class    0
dtype: int64

In [72]:
ttt_dataframe.head()

  TL TM TR ML MM MR BL BM BR  class
0  x  x  x  x  o  o  x  o  o   True
1  x  x  x  x  o  o  o  x  o   True
2  x  x  x  x  o  o  o  o  x   True
3  x  x  x  x  o  o  o  b  b   True
4  x  x  x  x  o  o  b  o  b   True

Separate input and target

In [99]:
X = ttt_dataframe.drop(columns=["class"])

y = ttt_dataframe["class"]
y = y.astype(int)
y.shape
print(y.value_counts())

class
1    626
0    332
Name: count, dtype: int64

Convert the categorical values to numeric in all columns.

In [74]:
#make y 0 and 1

In [75]:
import sklearn
from sklearn.preprocessing import OneHotEncoder

In [76]:
encoder = OneHotEncoder(drop = 'first', sparse_output=False)
X_encoded = encoder.fit_transform(X)

column_names = encoder.get_feature_names_out(X.columns)

X_encoded_df = pd.DataFrame(X_encoded, columns=column_names)

print(X_encoded_df.head())
print(np.shape(X_encoded_df))

   TL_o  TL_x  TM_o  TM_x  TR_o  TR_x  ML_o  ML_x  MM_o  MM_x  MR_o  MR_x  \
0   0.0   1.0   0.0   1.0   0.0   1.0   0.0   1.0   1.0   0.0   1.0   0.0
1   0.0   1.0   0.0   1.0   0.0   1.0   0.0   1.0   1.0   0.0   1.0   0.0
2   0.0   1.0   0.0   1.0   0.0   1.0   0.0   1.0   1.0   0.0   1.0   0.0
3   0.0   1.0   0.0   1.0   0.0   1.0   0.0   1.0   1.0   0.0   1.0   0.0
4   0.0   1.0   0.0   1.0   0.0   1.0   0.0   1.0   1.0   0.0   1.0   0.0

   BL_o  BL_x  BM_o  BM_x  BR_o  BR_x
0   0.0   1.0   1.0   0.0   1.0   0.0
1   1.0   0.0   0.0   1.0   1.0   0.0
2   1.0   0.0   1.0   0.0   0.0   1.0
3   1.0   0.0   0.0   0.0   0.0   0.0
4   0.0   0.0   1.0   0.0   0.0   0.0
(958, 18)

Normalize the input data

In [77]:
from sklearn.preprocessing import StandardScaler

In [78]:
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X_encoded_df)

X_scaled_df = pd.DataFrame(X_scaled, columns=column_names)

X_scaled_df.head()

,TL_o,TL_x,TM_o,TM_x,TR_o,TR_x,ML_o,ML_x,MM_o,MM_x,MR_o,MR_x,BL_o,BL_x,BM_o,BM_x,BR_o,BR_x
0,-0.733294,1.136603,-0.724898,1.238706,-0.733294,1.136603,-0.724898,1.238706,1.348201,-0.957079,1.379504,-0.807294,-0.733294,1.136603,1.379504,-0.807294,1.363709,-0.879815
1,-0.733294,1.136603,-0.724898,1.238706,-0.733294,1.136603,-0.724898,1.238706,1.348201,-0.957079,1.379504,-0.807294,1.363709,-0.879815,-0.724898,1.238706,1.363709,-0.879815
2,-0.733294,1.136603,-0.724898,1.238706,-0.733294,1.136603,-0.724898,1.238706,1.348201,-0.957079,1.379504,-0.807294,1.363709,-0.879815,1.379504,-0.807294,-0.733294,1.136603
3,-0.733294,1.136603,-0.724898,1.238706,-0.733294,1.136603,-0.724898,1.238706,1.348201,-0.957079,1.379504,-0.807294,1.363709,-0.879815,-0.724898,-0.807294,-0.733294,-0.879815
4,-0.733294,1.136603,-0.724898,1.238706,-0.733294,1.136603,-0.724898,1.238706,1.348201,-0.957079,1.379504,-0.807294,-0.733294,-0.879815,1.379504,-0.807294,-0.733294,-0.879815

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [79]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_scaled_df, y, test_size=0.2, random_state=42)

In [112]:
import tensorflow.keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from keras.optimizers import Adam

num_classes = 2
batch_size= 64
epochs = 20

model = Sequential()
model.add(Dense(32, activation='relu', input_shape=(18,)))
model.add(Dropout(0.2))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(num_classes, activation='softmax'))

opt = Adam(learning_rate = 0.001)

model.compile(loss='sparse_categorical_crossentropy',
              optimizer = opt,
              metrics=['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [113]:
model.summary()

Model: "sequential_14"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_22 (Dense)                │ (None, 32)             │           608 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_14 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_23 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_15 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_24 (Dense)                │ (None, 2)              │           130 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,850 (11.13 KB)

 Trainable params: 2,850 (11.13 KB)

 Non-trainable params: 0 (0.00 B)

In [114]:
# fit the training data

history = model.fit(X_train, y_train,
                    batch_size=batch_size,
                    epochs=epochs,
                    verbose=1,
                    validation_data=(X_test, y_test))

Epoch 1/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 27ms/step - accuracy: 0.4752 - loss: 0.7687 - val_accuracy: 0.6169 - val_loss: 0.6586
Epoch 2/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6240 - loss: 0.6663 - val_accuracy: 0.6104 - val_loss: 0.6525
Epoch 3/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6645 - loss: 0.6370 - val_accuracy: 0.6429 - val_loss: 0.6245
Epoch 4/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6749 - loss: 0.5950 - val_accuracy: 0.6883 - val_loss: 0.5977
Epoch 5/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7010 - loss: 0.5618 - val_accuracy: 0.7078 - val_loss: 0.5827
Epoch 6/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7154 - loss: 0.5632 - val_accuracy: 0.7208 - val_loss: 0.5691
Epoch 7/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7245 - loss: 0.5403 - val_accuracy: 0.7273 - val_loss: 0.5609
Epoch 8/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7141 - loss: 0.5393 - val_accuracy: 0.7338 - val_loss: 0.5452
Epoch 9/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7389 - loss: 0.5279 - val_accuracy: 0.7468 - val_loss: 0.5309
Epoch 10/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7533 - loss: 0.5085 - val_accuracy: 0.7403 - val_loss: 0.5185
Epoch 11/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7689 - loss: 0.4958 - val_accuracy: 0.7532 - val_loss: 0.5086
Epoch 12/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7689 - loss: 0.4731 - val_accuracy: 0.7792 - val_loss: 0.4951
Epoch 13/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7663 - loss: 0.4751 - val_accuracy: 0.7857 - val_loss: 0.4826
Epoch 14/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7794 - loss: 0.4457 - val_accuracy: 0.7857 - val_loss: 0.4698
Epoch 15/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8081 - loss: 0.4312 - val_accuracy: 0.7922 - val_loss: 0.4586
Epoch 16/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7937 - loss: 0.4249 - val_accuracy: 0.8182 - val_loss: 0.4408
Epoch 17/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7833 - loss: 0.4457 - val_accuracy: 0.8312 - val_loss: 0.4231
Epoch 18/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8211 - loss: 0.3944 - val_accuracy: 0.8377 - val_loss: 0.4131
Epoch 19/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8107 - loss: 0.4085 - val_accuracy: 0.8377 - val_loss: 0.3976
Epoch 20/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8355 - loss: 0.3732 - val_accuracy: 0.8377 - val_loss: 0.3918

In [115]:
model.save('tic_tac_toe_model.keras')

## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [116]:
loaded_model = keras.models.load_model('tic_tac_toe_model.keras')

In [134]:
#pick random rows from test set
X_test, X_few_rows, y_test, y_few_rows = train_test_split(X_test, y_test, test_size=0.05, random_state=42)

#make predictions
predicted = loaded_model.predict(X_few_rows)

predicted_values = np.argmax(predicted, axis=1)
true_values = y_few_rows.values

for i in range(len(predicted_values)):
  if predicted_values[i] == true_values[i]:
    print("Correct prediction!")
  else:
    print("Incorrect prediction!")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step
Incorrect prediction!
Correct prediction!
Correct prediction!
Correct prediction!

In [136]:
score = loaded_model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Test loss: 0.3839891850948334
Test accuracy: 0.8059701323509216

## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [143]:

num_classes = 2
batch_size= 64
epochs = 20

model = Sequential()
model.add(Dense(32, activation='relu', input_shape=(18,)))
model.add(Dropout(0.2))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(num_classes, activation='softmax'))

opt = Adam(learning_rate = 0.01)

model.compile(loss='sparse_categorical_crossentropy',
              optimizer = opt,
              metrics=['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [144]:
history = model.fit(X_train, y_train,
                    batch_size=batch_size,
                    epochs=epochs,
                    verbose=1,
                    validation_data=(X_test, y_test))

Epoch 1/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 3s 43ms/step - accuracy: 0.6514 - loss: 0.6351 - val_accuracy: 0.7313 - val_loss: 0.5508
Epoch 2/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7598 - loss: 0.5143 - val_accuracy: 0.8209 - val_loss: 0.4375
Epoch 3/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7637 - loss: 0.4521 - val_accuracy: 0.8955 - val_loss: 0.3187
Epoch 4/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8499 - loss: 0.3388 - val_accuracy: 0.9403 - val_loss: 0.1997
Epoch 5/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8773 - loss: 0.2932 - val_accuracy: 0.9701 - val_loss: 0.1302
Epoch 6/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9164 - loss: 0.2001 - val_accuracy: 0.9552 - val_loss: 0.1267
Epoch 7/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9439 - loss: 0.1565 - val_accuracy: 0.9701 - val_loss: 0.0772
Epoch 8/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9452 - loss: 0.1362 - val_accuracy: 0.9851 - val_loss: 0.0754
Epoch 9/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9491 - loss: 0.1222 - val_accuracy: 0.9851 - val_loss: 0.0387
Epoch 10/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9530 - loss: 0.1134 - val_accuracy: 0.9701 - val_loss: 0.0589
Epoch 11/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9621 - loss: 0.0994 - val_accuracy: 0.9701 - val_loss: 0.0470
Epoch 12/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9687 - loss: 0.0748 - val_accuracy: 0.9851 - val_loss: 0.0638
Epoch 13/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9739 - loss: 0.0546 - val_accuracy: 0.9851 - val_loss: 0.0748
Epoch 14/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9804 - loss: 0.0423 - val_accuracy: 0.9851 - val_loss: 0.0514
Epoch 15/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9778 - loss: 0.0757 - val_accuracy: 0.9851 - val_loss: 0.0586
Epoch 16/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9778 - loss: 0.0642 - val_accuracy: 0.9701 - val_loss: 0.1194
Epoch 17/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9817 - loss: 0.0480 - val_accuracy: 0.9701 - val_loss: 0.1024
Epoch 18/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9843 - loss: 0.0332 - val_accuracy: 0.9701 - val_loss: 0.0887
Epoch 19/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9883 - loss: 0.0283 - val_accuracy: 0.9701 - val_loss: 0.1024
Epoch 20/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9869 - loss: 0.0289 - val_accuracy: 0.9851 - val_loss: 0.0797

**Which approach(es) did you find helpful to improve your model performance?**

Just trial and error of playing around with additional layers and adjusting the learning rate.